FROM debian:stretch
#FROM alpine:3.4

MAINTAINER Tit Petric <tit.petric@monotek.net>

#RUN apk --update add ucarp bash tcpdump
RUN apt-get -q update && apt-get -qy install ucarp tcpdump && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*

COPY ucarp/ /ucarp/

WORKDIR /ucarp

ENTRYPOINT ["/ucarp/run.sh"]
