FROM debian:stretch

MAINTAINER Tit Petric <tit.petric@monotek.net>

ENV DOCKER_ENV=debian

RUN apt-get -q update && apt-get -qy install ucarp ssmtp tcpdump && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*

COPY ucarp/ /ucarp/

WORKDIR /ucarp

ENTRYPOINT ["/ucarp/run.sh"]
